### ISSUE TITLE
Basic request system

### ISSUE THREAD

**Issue by markusgut** [openbookshelf/openbookshelf#5]
- [ ] Send request for media item
- [ ] Answer media requests
- [ ] Accept/deny request
